[package]
name = "ulse"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.14", features = ["derive"] }
env_logger = "0.11.6"
pollster = "0.4"
wgpu = "24.0.0"
winit = { version = "0.30.8", features = ["android-native-activity"] }
